### ISSUE TITLE
Suggestion: Config to block default videos from playing, or a user-defined list on what videos can play

### ISSUE THREAD

**Issue by dopadream** [I8aDOG/LC_TitleVideos#1]
I would like to include this in my modpack without the possibility of the default videos playing as I had planned to record my own. Do you think you could add something like this? Simply deleting the videos on my end won't be recognized on thunderstore's side and people who download it will still see the default videos. Can you add some way to overwrite them?

**Comment by NotCasey** [comment]
Thank you for the feedback, I'm new to uploading mods to Thunderstore. All of the built-in videos have been added to a 'DefaultTitleVideos' folder, which can now be disabled from being scanned through the configuration file.

**Comment by dopadream** [comment]
You're the goat
